apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: itoo-basicinfo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: itoo-basicinfo
    spec:
      containers:
      - name: itoo-basicinfo
        image: reg.dynamicharbor.com/web/othertomcat:2.0
        resources:
          requests:
            cpu: 500m
        volumeMounts:
        - name: httpd-storage
          mountPath: /usr/local/tomcat/webapps
        ports:
        - containerPort: 80
      volumes:
      - name: httpd-storage
        hostPath:
          path: /usr/local/src/basicInfo-tomcat