apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-tomcat
    spec:
      containers:
      - name: k8s-tomcat
        image: daocloud.io/library/tomcat:6.0-jre7
      
